# This file lists the dependencies needed to build and test all of ipyvue-flatsurf.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: ipyvue-flatsurf-build
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib-base
  - pyflatsurf >=3.9.2,<4
  # functools.cache requires Python 3.9
  - python >=3.9
  - pytest
  - pytest-xdist
  - ruamel.yaml
  - sage-flatsurf >=0.5,<0.6
  - sagelib
  - scipy
  - surface-dynamics >=0.4.7
  - sympy
  - pip
  - pip:
    - flipper
    - jupyter_ui_poll >=0.2.1,<0.3
    - ipymuvue >=0.3.0,<0.7.0
