# This environment.yml can be used to create a conda environment with
# ipyvue-flatsurf and all its dependencies installed. It is used for our demo
# binders.
name: binder
channels:
  - flatsurf
  - conda-forge
dependencies:
  # functools.cache requires Python 3.9
  - python=3.9
  - sagelib
  - sympy
  - scipy
  - ipywidgets
  # Work around https://github.com/flatsurf/ipyvue-flatsurf/issues/38
  - notebook>=6.0.0,<6.3.0
  - pyflatsurf>=3.9.2,<4
  - matplotlib-base
  - surface-dynamics>=0.4.7
  # ipyvue-flatsurf relies on the availability of Decomposition in
  # flatsurf.geometry.gl2r_orbit_closure which was dropped in 0.4.4
  - sage-flatsurf >=0.4.0,<0.4.4
  - jupytext
  - ruamel.yaml
  - pip
  - pip:
    - flipper
    - ipyvue-async >=0.1.0,<0.2
    - jupyter_ui_poll >=0.2.1,<0.3
    - ipyvue-flatsurf==0.5.4
