# This environment.yml can be used to create a conda environment with
# ipyvue-flatsurf and all its dependencies installed. It is used for our demo
# binders.
name: binder
channels:
  - conda-forge
dependencies:
  - sagelib
  - sympy
  - scipy
  - ipywidgets
  - jupyterlab
  - pyflatsurf>=3.9.2,<4
  - matplotlib-base
  - surface-dynamics>=0.4.7
  - sage-flatsurf >=0.5,<0.6
  - jupytext
  - ruamel.yaml
  - pip
  - pip:
    - flipper
    - jupyter_ui_poll >=0.2.1,<0.3
    - ipymuvue >=0.3.0,<0.7.0
    - ipyvue-flatsurf==0.6.2
